#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_ITERATIONS_SMALL 32
#define MAX_ITERATIONS 16384

#define MAP_WIDTH 80
#define MAP_HEIGHT 21

#define WORLD_X_SPAN 200
#define WORLD_Y_SPAN 200

#define WORLD_WIDTH 401
#define WORLD_HEIGHT 401

#define PADDING 3
#define GATE_PADDING 7

#endif
